### ISSUE TITLE
Erreur à l'installation

### ISSUE THREAD

**Issue by rdalverny** [cshw/plugins#11]
* module 1.0.1
 * PrestaShop 1.5.x
 * PHP 5.6.17-0+deb8u1
 * erreur `[PrestaShop] Fatal error in module AdminController: Class name must be a valid object or a string` à l'installation

**Comment by rdalverny** [comment]
Je n'arrive pas à reproduire en local sur une 1.5... Est-ce que ce serait le formulaire de création de compte ? (peu utilisé donc sans doute un cas limite). Version 1.1 publiée, sans ce formulaire, plus quelques nettoyages.

**Comment by luileito** [comment]
I confirm this also happens in a fresh installation of v1.5.0.17-stable.

**Comment by rdalverny** [comment]
@luileito thanks for the feedback! Could you detail with which version of the module and at which step (install, configuration, which form)?

**Comment by luileito** [comment]
It's a private module I'm developing. It happens right after installation, when I click on the configure link. 

The error seems to start in `processAdd()` from `AdminController.php`, so I'm using the initial cross-check from later PS versions to avoid PHP throwing a Fatal error:
```php
public function processAdd()
{
  if (!isset($this->className) || empty($this->className))
    return false;
  ...
```
I confirm this issue doesn't happen in later PS versions.

**Comment by rdalverny** [comment]
Oh ok. I was wondering how you found this very issue, thought you were trying our module. :smile: 
Thanks a lot! :+1: 
Now I'm trying to override AdminController... that's fun.

**Comment by rdalverny** [comment]
An other echo tells me that supporting the very first stable release of 1.5 may not be worth the trouble now.

**Comment by rdalverny** [comment]
Closing, wontfix. Anyway, thanks a lot for the hint @luileito!
